---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: flux-system
spec:
  releaseName: calico
  targetNamespace: tigera-operator
  storageNamespace: tigera-operator
  interval: 1m0s
  chart:
    spec:
      chart: tigera-operator
      sourceRef:
        kind: HelmRepository
        name: projectcalico
  values:
    apiService:
      create: true
  install:
    createNamespace: true
