---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: flux-system
spec:
  releaseName: calico
  interval: 10m0s
  chart:
    spec:
      chart: tigera-operator
      version: v3.20.0
      sourceRef:
        kind: HelmRepository
        name: projectcalico
  install:
    createNamespace: true
  values:
    installation:
      kubernetesProvider: EKS

